package com.picstore.backend.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDateTime;

/* JPA entity representing a species observation record. Each observation stores details about a wildlife/nature sighting. */
@Entity
@Table(name = "observations")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Observation {
    /* Unique identifier for the observation record - auto-generated by the database */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /* Common name of the species that was observed */
    private String speciesName;

    /* Optional user-provided notes or description of the sighting, limited to 200 characters */
    @Column(length = 200)
    private String description;

    /* File path or URI to the captured image of the observation */
    private String imagePath;

    /* Latitude coordinate of the observation location */
    private Double latitude;

    /* Longitude coordinate of the observation location */
    private Double longitude;

    /* Human-readable country resolved from GPS coordinates via reverse-geocoding */
    private String country;

    /* Human-readable city or subregion resolved from GPS coordinates via reverse-geocoding */
    private String city;

    /* Timestamp indicating when this observation was recorded */
    private LocalDateTime timestamp;

    /* Category ID linking this observation to a species category (e.g., Mammals, Birds, Insects) */
    private int categoryId;

    /* Privacy setting configuring visibility (e.g., PUBLIC, PRIVATE, FRIENDS) */
    @Column(nullable = false)
    private String privacySetting = "PUBLIC";

    /* Relational linkage tying this observation metadata record directly to its creating user account */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /* JPA lifecycle callback that automatically sets the timestamp to the current date/time when the observation is first persisted to the database. */
    @PrePersist
    protected void onCreate() {
        this.timestamp = LocalDateTime.now();
    }
}