# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/picstore
spring.datasource.username=postgres
spring.datasource.password=K<`SB5g0a8(r
spring.datasource.driver-class-name=org.postgresql.Driver

# Permanent local disk folder configuration
upload.path=C:/Users/jukel/PicstoreImages/

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable open-in-view for performance guidelines
spring.jpa.open-in-view=false

# Maximum allowed size for a single uploaded file (e.g., 10MB)
spring.servlet.multipart.max-file-size=10MB

# Maximum allowed size for a whole multipart/form-data request
spring.servlet.multipart.max-request-size=10MB